[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"


[project]
name = "reachy_mini_app"
version = "0.1.0"
description = "Playground projekt"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "reachy-mini==1.7.1"
]
keywords = ["reachy-mini-app"]

[project.urls]
Plugin = "https://github.com/nolte/claude-reachy-mini"
SDK = "https://github.com/pollen-robotics/reachy_mini"
Specs = "https://github.com/nolte/claude-reachy-mini/tree/develop/spec/reachy-mini/"

[project.entry-points."reachy_mini_apps"]
reachy_mini_app = "reachy_mini_app.main:ReachyMiniApp"

[tool.setuptools]
package-dir = { "" = "." }
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
reachy_mini_app = ["**/*"] # Also include all non-.py files
