name: Release CD — Deliver docs

on:
  release:
    types: [published]

permissions:
  contents: write
  id-token: write
  pages: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  publish-docs:
    uses: nolte/gh-plumbing/.github/workflows/reusable-mkdocs.yaml@v1.1.15
    with:
      requirements: docs/requirements.txt
