name: Release CD — Refresh main

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  refresh-main:
    uses: nolte/gh-plumbing/.github/workflows/reusable-release-cd-refresh-master.yml@v1.1.15
    with:
      target_branch: main
